CREATE DATABASE IF NOT EXISTS patient360_prod;
SHOW DATABASES LIKE 'PATIENT360_PROD';

CREATE SCHEMA IF NOT EXISTS PATIENT360_PROD.EHR_RAW;
CREATE SCHEMA IF NOT EXISTS PATIENT360_PROD.STAGING;
CREATE SCHEMA IF NOT EXISTS PATIENT360_PROD.INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS PATIENT360_PROD.MART;


SELECT CURRENT_REGION();

USE ROLE ACCOUNTADMIN;
CREATE STORAGE INTEGRATION s3_neodaux_int
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = 'S3'
    ENABLED = TRUE
    STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::394442256887:role/snowflake-neodaux-si-role'
    STORAGE_ALLOWED_LOCATIONS = ('s3://p360-healthcare-raw/');

DESC INTEGRATION s3_neodaux_int;

CREATE OR REPLACE STAGE aws_extstg
    URL = 's3://p360-healthcare-raw/ehr/'
    STORAGE_INTEGRATION = s3_neodaux_int;

list @patient360_prod.ehr_raw.aws_extstg;
