show databases;
show schemas;

SHOW TABLES IN SCHEMA PATIENT360_PROD.EHR_RAW;
SHOW STAGES IN SCHEMA PATIENT360_PROD.EHR_RAW;

LIST @patient360_prod.ehr_raw.aws_extstg;

--create external stages
CREATE OR REPLACE STAGE PATIENT360_PROD.EHR_RAW.AWS_PROCESSED_EHR_STG
    URL = 's3://p360-healthcare-raw/processed/ehr/'
    STORAGE_INTEGRATION = s3_neodaux_int;

CREATE OR REPLACE STAGE PATIENT360_PROD.EHR_RAW.AWS_PROCESSED_FHIR_STG
    URL = 's3://p360-healthcare-raw/processed/fhir/'
    STORAGE_INTEGRATION = s3_neodaux_int;

LIST @PATIENT360_PROD.EHR_RAW.AWS_PROCESSED_EHR_STG;
LIST @PATIENT360_PROD.EHR_RAW.AWS_PROCESSED_FHIR_STG;

--Step 1 — Create the CSV file format
CREATE OR REPLACE FILE FORMAT PATIENT360_PROD.EHR_RAW.CSV_FORMAT
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('', 'NULL');

SHOW FILE FORMATS IN SCHEMA PATIENT360_PROD.EHR_RAW;

--Step 2 — Inspect the processed patients file
SELECT *
FROM @PATIENT360_PROD.EHR_RAW.AWS_PROCESSED_EHR_STG/patients.csv
(FILE_FORMAT => 'PATIENT360_PROD.EHR_RAW.CSV_FORMAT')
LIMIT 5;

SELECT
    $1,
    $2,
    $3,
    $4,
    $5
FROM @PATIENT360_PROD.EHR_RAW.AWS_PROCESSED_EHR_STG/patients.csv
(
    FILE_FORMAT => 'PATIENT360_PROD.EHR_RAW.CSV_FORMAT'
)
LIMIT 5;

--Snowflake infer the staged file schema
SELECT
    COLUMN_NAME,
    TYPE,
    NULLABLE,
    EXPRESSION
FROM TABLE(
    INFER_SCHEMA(
        LOCATION => '@PATIENT360_PROD.EHR_RAW.AWS_PROCESSED_EHR_STG/patients.csv',
        FILE_FORMAT => 'PATIENT360_PROD.EHR_RAW.CSV_FORMAT',
        IGNORE_CASE => TRUE
    )
)
ORDER BY ORDER_ID;

--file format for infer schema
CREATE OR REPLACE FILE FORMAT PATIENT360_PROD.EHR_RAW.CSV_HEADER_FORMAT
    TYPE = CSV
    PARSE_HEADER = TRUE
    FIELD_OPTIONALLY_ENCLOSED_BY = '"';

--ispect column names using infer schema
SELECT
    COLUMN_NAME,
    TYPE,
    NULLABLE,
    EXPRESSION
FROM TABLE(
    INFER_SCHEMA(
        LOCATION => '@PATIENT360_PROD.EHR_RAW.AWS_PROCESSED_EHR_STG/patients.csv',
        FILE_FORMAT => 'PATIENT360_PROD.EHR_RAW.CSV_HEADER_FORMAT',
        IGNORE_CASE => TRUE
    )
)
ORDER BY ORDER_ID;

--Create the Parquet file format
CREATE FILE FORMAT IF NOT EXISTS PATIENT360_PROD.EHR_RAW.PARQUET_FORMAT
    TYPE = PARQUET;