CREATE TABLE IF NOT EXISTS PATIENT360_PROD.EHR_RAW.RAW_ENCOUNTERS
USING TEMPLATE (
    SELECT ARRAY_AGG(
        OBJECT_CONSTRUCT(*)
    ) WITHIN GROUP (ORDER BY ORDER_ID)
    FROM TABLE(
        INFER_SCHEMA(
            LOCATION => '@PATIENT360_PROD.EHR_RAW.AWS_PROCESSED_EHR_STG/encounters.parquet',
            FILE_FORMAT => 'PATIENT360_PROD.EHR_RAW.PARQUET_FORMAT'
        )
    )
);