CREATE TABLE IF NOT EXISTS PATIENT360_PROD.CLAIMS_RAW.RAW_CLAIMS
USING TEMPLATE (
    SELECT ARRAY_AGG(
        OBJECT_CONSTRUCT(*)
    ) WITHIN GROUP (ORDER BY ORDER_ID)
    FROM TABLE(
        INFER_SCHEMA(
            LOCATION => '@PATIENT360_PROD.CLAIMS_RAW.AWS_PROCESSED_CLAIMS_STG/claims.csv',
            FILE_FORMAT => 'PATIENT360_PROD.CLAIMS_RAW.CSV_HEADER_FORMAT',
            IGNORE_CASE => TRUE
        )
    )
);