CREATE TABLE IF NOT EXISTS PATIENT360_PROD.AUDIT.RAW_LOAD_AUDIT (
    AUDIT_ID NUMBER AUTOINCREMENT,
    TABLE_NAME VARCHAR,
    SOURCE_FILE VARCHAR,
    ROWS_LOADED NUMBER,
    LOAD_STATUS VARCHAR,
    DAG_ID VARCHAR,
    DAG_RUN_ID VARCHAR,
    TASK_ID VARCHAR,
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);