-- Create Patient RAW table if it does not exist.

CREATE TABLE IF NOT EXISTS PATIENT360_PROD.EHR_RAW.RAW_PATIENTS
USING TEMPLATE (
    SELECT ARRAY_AGG(
        OBJECT_CONSTRUCT(*)
    ) WITHIN GROUP (ORDER BY ORDER_ID)
    FROM TABLE(
        INFER_SCHEMA(
            LOCATION => '@PATIENT360_PROD.EHR_RAW.AWS_PROCESSED_EHR_STG/patients.csv',
            FILE_FORMAT => 'PATIENT360_PROD.EHR_RAW.CSV_HEADER_FORMAT',
            IGNORE_CASE => TRUE
        )
    )
);