-- Load processed FHIR Labs from S3 into Snowflake RAW.

COPY INTO PATIENT360_PROD.EHR_RAW.RAW_LABS
FROM @PATIENT360_PROD.EHR_RAW.AWS_PROCESSED_FHIR_STG/lab_observations.csv
FILE_FORMAT = (
    FORMAT_NAME = 'PATIENT360_PROD.EHR_RAW.CSV_HEADER_FORMAT'
)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'ABORT_STATEMENT';