-- Load processed conditions from S3 into Snowflake RAW.

COPY INTO PATIENT360_PROD.EHR_RAW.RAW_CONDITIONS
FROM @PATIENT360_PROD.EHR_RAW.AWS_PROCESSED_EHR_STG/conditions.csv
FILE_FORMAT = (
    FORMAT_NAME = 'PATIENT360_PROD.EHR_RAW.CSV_HEADER_FORMAT'
)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'ABORT_STATEMENT';