COPY INTO PATIENT360_PROD.CLAIMS_RAW.RAW_CLAIM_TRANSACTIONS
FROM @PATIENT360_PROD.CLAIMS_RAW.AWS_PROCESSED_CLAIMS_STG/claims_transactions.csv
FILE_FORMAT = (
    FORMAT_NAME = 'PATIENT360_PROD.CLAIMS_RAW.CSV_HEADER_FORMAT'
)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'ABORT_STATEMENT';